### ISSUE TITLE
Integrate Gitlab

### ISSUE THREAD

**Issue by M0dM** [layerssss/sshkeyd#2]
Hi,

I am really interested to use this peace of software to manage ssh keys over my servers.
Did you plan to integrate gitlab support for ssh keys retrieving.

 If you did not plan to do it soon, could you give me some usefull information to develop this by myself and submit it by pull request ?

Also did you produce a "how to contribute" documentation ? 

M0dM

**Comment by layerssss** [comment]
Great, a pull request will be great. Just some quick notes to get you into development.
1. get the code 
2. get the environment ( nodejs )
3. install dependencies (into ./node_modules ): `npm install`
4. launch the server: `./bin/sshkeyd`
5. after each time you modify the code, you need to press ctrl-c and restart the server, because there's no magic reloading :(
6. most of the code is in `lib/sshkeyd.iced`, it's an old express.js server written with [IcedCoffeeScript](http://maxtaco.github.io/coffee-script/)
7. there are some interface templates written in Jade in `views/`, in case you need to modify them.
8. the program manages a config file `~/.sshkeyd.json`, which is defined in `lib/cli.iced`, it will be great if you can store the options (to use GitHub or GitLab, and GitLab api address, etc) here.

just ping me if you come up with any question

**Comment by M0dM** [comment]
Ok, thanks for the answer.
I will try to look at this shortly.
